export const surpriseMePrompts = [
    'an armchair in the shape of an avocado',
    'a surrealist dream-like oil painting by Salvador Dalí of a cat playing checkers',
    'teddy bears shopping for groceries in Japan, ukiyo-e',
    'an oil painting by Matisse of a humanoid robot playing chess',
    'panda mad scientist mixing sparkling chemicals, digital art',
    "a macro 35mm photograph of two mice in Hawaii, they're each wearing tiny swimsuits and are carrying tiny surf boards, digital art",
    '3D render of a cute tropical fish in an aquarium on a dark blue background, digital art',
    'an astronaut lounging in a tropical resort in space, vaporwave',
    'an oil painting portrait of a capybara wearing medieval royal robes and an ornate crown on a dark background',
    'a stained glass window depicting a hamburger and french fries',
    'a pencil and watercolor drawing of a bright city in the future with flying cars',
    'a sunlit indoor lounge area with a pool with clear water and another pool with translucent pastel pink water, next to a big window, digital art',
    'a fortune-telling shiba inu reading your fate in a giant hamburger, digital art',
    '"a sea otter with a pearl earring" by Johannes Vermeer',
    'an oil pastel drawing of an annoyed cat in a spaceship',
    'a painting of a fox in the style of Starry Night',
    'a bowl of soup that looks like a monster, knitted out of wool',
    'A plush toy robot sitting against a yellow wall',
    'A synthwave style sunset above the reflecting water of the sea, digital art',
    'Two futuristic towers with a skybridge covered in lush foliage, digital art',
    'A 3D render of a rainbow colored hot air balloon flying above a reflective lake',
    'A comic book cover of a superhero wearing headphones',
    'A centered explosion of colorful powder on a black background',
    'A photo of a Samoyed dog with its tongue out hugging a white Siamese cat',
    'A photo of a white fur monster standing in a purple room',
    "A photo of Michelangelo's sculpture of David wearing headphones djing",
    'A Samurai riding a Horse on Mars, lomography',
    'A modern, sleek Cadillac drives along the Gardiner expressway with downtown Toronto in the background, with a lens flare, 50mm photography',
    'A realistic photograph of a young woman with blue eyes and blonde hair',
    'A man standing in front of a stargate to another dimension',
    'Spongebob Squarepants in the Blair Witch Project',
    'A velociraptor working at a hotdog stand, lomography',
    'A man walking through the bustling streets of Kowloon at night, lit by many bright neon shop signs, 50mm lens',
    'A BBQ that is alive, in the style of a Pixar animated movie',
    'A futuristic cyborg dance club, neon lights',
    'The long-lost Star Wars 1990 Japanese Anime',
    'A Synthwave Hedgehog, Blade Runner Cyberpunk',
    'An astronaut encountering an alien life form on a distant planet, photography',
    'A Dinosaur exploring Cape Town, photography',
    'A Man falling in Love with his Computer, digital art',
    'A photograph of a cyborg exploring Tokyo at night, lomography',
    'Dracula walking down the street of New York City in the 1920s, black and white photography',
    'Synthwave aeroplane',
    'A man wanders through the rainy streets of Tokyo, with bright neon signs, 50mm',
    'A Space Shuttle flying above Cape Town, digital art',
    'A giant octopus playing soccer with a group of flamingos',
    'A snake made entirely of cupcakes slithering through a field of flowers',
    'A tree made of rainbows with birds nesting in its branches',
    ' A group of penguins riding bicycles on a rainbow',
    'A hot air balloon made of cheese flying over a forest of broccoli trees',
    'A dragon made of crystal with a flower garden inside its belly',
    'A mermaid riding a unicorn in a sea of cotton candy',
    'A robot made of spaghetti and meatballs serving food to a group of people',
    'A house made of books with a cat sleeping on the roof',
    'A castle made of ice cream with a moat filled with chocolate sauce',
    'A monster made of clouds raining down on a city made of candy',
    'A rocket ship made of flowers blasting off into space',
    'A snowman made of fire roasting marshmallows',
    'A turtle made of fruit with a strawberry shell',
    'A vampire made of jelly beans drinking a glass of cherry soda',
    'A giraffe made of candy canes eating a giant lollipop',
    'A robot made of feathers playing a guitar',
    'A butterfly made of crystals with a garden on its wings',
    'A cactus made of ice cream with a cherry on top',
    'A spaceship made of popcorn with a buttery trail',
    'A snake made of spaghetti with meatball eyes',
    'A pumpkin made of candy with a bat flying out of it',
    "A robot made of gears with a bird's nest on its head",
    'A castle made of cheese with a river of tomato sauce',
    'A house made of candy canes with a gingerbread roof',
    'A tree made of cotton candy with a carousel inside',
    'A unicorn made of bubbles with a rainbow mane',
    'A robot made of flowers with a butterfly friend',
    'A dragon made of candy with a licorice tongue',
    'A city made of clouds with a rainbow bridge',
    "A tree made of books with a bird's nest in its branches",
    'A robot made of crystals playing soccer with a group of aliens',
    'A turtle made of clouds with a rainbow shell',
    'A house made of cupcakes with a cherry on top',
    'A monster made of fruit with a kiwi tongue',
    'A tree made of jelly beans with a lollipop garden',
    'A castle made of clouds with a lightning moat',
    'A robot made of cotton candy with a bird friend',
    'A spaceship made of candy with a chocolate engine',
    "A tree made of gears with a bird's nest in its branches",
    "A dragon made of feathers with a bird's nest on its back",
    'A unicorn made of rainbows with a cloud mane',
    'A city made of candy canes with a gingerbread bridge',
    'A robot made of ice cream with a cherry on top',
    'A house made of clouds with a rainbow roof',
    'A tree made of spaghetti with a meatball nest',
    'A monster made of crystals with a diamond tongue',
    'A robot made of jelly beans with a gummy bear friend',
    'A spaceship made of flowers with a butterfly pilot',
    'A turtle made of candy with a cherry shell',
    'A bird made of toast',
    'A tree with a face made of bananas',
    'A bear made of chocolate bars',
    'A dinosaur made of clouds',
    'A house with a chimney made of candy canes',
    'A train made of donuts',
    'A robot made of rubber ducks',
    'A snail made of spaghetti and meatballs',
    'A submarine made of cheese',
    'A spider made of candy',
    'A tree with a face made of clocks',
    'A car made of bread',
    'A giraffe made of spaghetti',
    'A bicycle made of ice cream cones',
    'A boat made of flowers',
];